q

diff --git a/.github/workflows/create_environment.yml b/.github/workflows/create_environment.yml
--- a/.github/workflows/create_environment.yml
+++ b/.github/workflows/create_environment.yml
@@ -35,9 +35,18 @@ jobs:
         python .github/workflows/create_environment.py get_token \
             --client_id "${{ secrets.PORT_CLIENT_ID }}" \
             --client_secret "${{ secrets.PORT_CLIENT_SECRET }}"
+      continue-on-error: false
+
+    - name: Check if JWT token is obtained
+      run: |
+        if [ -z "${{ steps.get_token.outputs.token }}" ]; then
+          echo "Error: JWT Token not obtained."
+          exit 1
+        fi
 
     - name: Create environment
       id: create_environment
       run: |
-          python .github/workflows/create_environment.py create_environment
-
+        python .github/workflows/create_environment.py create_environment \
+            --token "${{ steps.get_token.outputs.token }}"
+      continue-on-error: false
